### ISSUE TITLE
Mistakes on legislator names

### ISSUE THREAD

**Issue by bshor** [votesmart/political-id-match#2]
[Paula Sandoval](https://en.wikipedia.org/wiki/Paula_Sandoval) from Colorado is mistakenly entered as Rafael Espinoza. Espinoza is a Denver councilmember, and has never been a state legislator. See, for example, [ourcompaigns](https://www.ourcampaigns.com/CandidateDetail.html?CandidateID=358394) here.

This error creeps into the main [Votesmart page here](https://votesmart.org/candidate/biography/30142/rafael-espinoza), where you can see the obvious mismatch.

The source of the error is likely Sandoval's election to the Denver council.

**Comment by bshor** [comment]
[E. Denise Lee](https://ballotpedia.org/E._Denise_Lee) from Florida (Votesmart ID 1633) is mistakenly entered as Katrina Brown, who is a merely a former Jacksonville city councilor. Lee is herself a city councilor

**Comment by bshor** [comment]
Richard LeBlanc from Michigan (ID 66901) is mistakenly entered as Glen Anderson. You can see this when you pull up Follow the Money's [entry for LeBlanc](https://www.followthemoney.org/entity-details?eid=152172), which is entity id 152172.

You can also see this on Votesmart's page, comparing the page text to the url [here](https://votesmart.org/candidate/key-votes/66901/richard-leblanc/68/women).

**Comment by bshor** [comment]
Sheldon Johnson from Minnesota (id 109221) is mistakenly entered as Kory Kath. You can see this when calling followthemoney's [entry for Johnson](https://www.followthemoney.org/entity-details?eid=6516096) which has entity id 6516096 as opposed to the [entry for Kath](https://www.followthemoney.org/entity-details?eid=6517877) which has entity id 6517877.

**Comment by bshor** [comment]
These issues were with respect to the May 2018 version of the data. I see a new commit was uploaded a few days ago; I'll now switch to that one for further testing.

**Comment by wrm5b** [comment]
Thank you for your interest in our work and your keen eye! We appreciate you reaching out. Follow-ups below:
- Sandoval has been manually fixed in our DB.
- Lee has been manually fixed in our DB.
- LeBlanc has been manually fixed in our DB.
- Johnson has been manually fixed in our DB.

These fixes will be reflected on political-id-match at the next update, which we plan to do within the next couple of months.

**Comment by bshor** [comment]
Great! I only point out the very few mistakes I found ... compared with the hundreds of thousands you got right :)
